package com.crab.entity;

public class ResourceRoleLinkKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource_role.resc_id
     *
     * @mbggenerated Fri Apr 24 13:16:32 CST 2015
     */
    private Integer rescId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource_role.role_id
     *
     * @mbggenerated Fri Apr 24 13:16:32 CST 2015
     */
    private Integer roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource_role.resc_id
     *
     * @return the value of t_resource_role.resc_id
     *
     * @mbggenerated Fri Apr 24 13:16:32 CST 2015
     */
    public Integer getRescId() {
        return rescId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource_role.resc_id
     *
     * @param rescId the value for t_resource_role.resc_id
     *
     * @mbggenerated Fri Apr 24 13:16:32 CST 2015
     */
    public void setRescId(Integer rescId) {
        this.rescId = rescId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource_role.role_id
     *
     * @return the value of t_resource_role.role_id
     *
     * @mbggenerated Fri Apr 24 13:16:32 CST 2015
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource_role.role_id
     *
     * @param roleId the value for t_resource_role.role_id
     *
     * @mbggenerated Fri Apr 24 13:16:32 CST 2015
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}