package com.crab.entity;

public class Resources {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resources.id
     *
     * @mbggenerated Thu Apr 23 15:14:51 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resources.name
     *
     * @mbggenerated Thu Apr 23 15:14:51 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resources.parentId
     *
     * @mbggenerated Thu Apr 23 15:14:51 CST 2015
     */
    private Integer parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resources.resKey
     *
     * @mbggenerated Thu Apr 23 15:14:51 CST 2015
     */
    private String reskey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resources.type
     *
     * @mbggenerated Thu Apr 23 15:14:51 CST 2015
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resources.resUrl
     *
     * @mbggenerated Thu Apr 23 15:14:51 CST 2015
     */
    private String resurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resources.level
     *
     * @mbggenerated Thu Apr 23 15:14:51 CST 2015
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resources.description
     *
     * @mbggenerated Thu Apr 23 15:14:51 CST 2015
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resources.id
     *
     * @return the value of t_resources.id
     *
     * @mbggenerated Thu Apr 23 15:14:51 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resources.id
     *
     * @param id the value for t_resources.id
     *
     * @mbggenerated Thu Apr 23 15:14:51 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resources.name
     *
     * @return the value of t_resources.name
     *
     * @mbggenerated Thu Apr 23 15:14:51 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resources.name
     *
     * @param name the value for t_resources.name
     *
     * @mbggenerated Thu Apr 23 15:14:51 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resources.parentId
     *
     * @return the value of t_resources.parentId
     *
     * @mbggenerated Thu Apr 23 15:14:51 CST 2015
     */
    public Integer getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resources.parentId
     *
     * @param parentid the value for t_resources.parentId
     *
     * @mbggenerated Thu Apr 23 15:14:51 CST 2015
     */
    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resources.resKey
     *
     * @return the value of t_resources.resKey
     *
     * @mbggenerated Thu Apr 23 15:14:51 CST 2015
     */
    public String getReskey() {
        return reskey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resources.resKey
     *
     * @param reskey the value for t_resources.resKey
     *
     * @mbggenerated Thu Apr 23 15:14:51 CST 2015
     */
    public void setReskey(String reskey) {
        this.reskey = reskey == null ? null : reskey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resources.type
     *
     * @return the value of t_resources.type
     *
     * @mbggenerated Thu Apr 23 15:14:51 CST 2015
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resources.type
     *
     * @param type the value for t_resources.type
     *
     * @mbggenerated Thu Apr 23 15:14:51 CST 2015
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resources.resUrl
     *
     * @return the value of t_resources.resUrl
     *
     * @mbggenerated Thu Apr 23 15:14:51 CST 2015
     */
    public String getResurl() {
        return resurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resources.resUrl
     *
     * @param resurl the value for t_resources.resUrl
     *
     * @mbggenerated Thu Apr 23 15:14:51 CST 2015
     */
    public void setResurl(String resurl) {
        this.resurl = resurl == null ? null : resurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resources.level
     *
     * @return the value of t_resources.level
     *
     * @mbggenerated Thu Apr 23 15:14:51 CST 2015
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resources.level
     *
     * @param level the value for t_resources.level
     *
     * @mbggenerated Thu Apr 23 15:14:51 CST 2015
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resources.description
     *
     * @return the value of t_resources.description
     *
     * @mbggenerated Thu Apr 23 15:14:51 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resources.description
     *
     * @param description the value for t_resources.description
     *
     * @mbggenerated Thu Apr 23 15:14:51 CST 2015
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}