package com.crab.entity;

public class Role {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.id
     *
     * @mbggenerated Thu Apr 23 15:14:51 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.name
     *
     * @mbggenerated Thu Apr 23 15:14:51 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.roleKey
     *
     * @mbggenerated Thu Apr 23 15:14:51 CST 2015
     */
    private String rolekey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.description
     *
     * @mbggenerated Thu Apr 23 15:14:51 CST 2015
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.enable
     *
     * @mbggenerated Thu Apr 23 15:14:51 CST 2015
     */
    private Integer enable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.id
     *
     * @return the value of t_role.id
     *
     * @mbggenerated Thu Apr 23 15:14:51 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.id
     *
     * @param id the value for t_role.id
     *
     * @mbggenerated Thu Apr 23 15:14:51 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.name
     *
     * @return the value of t_role.name
     *
     * @mbggenerated Thu Apr 23 15:14:51 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.name
     *
     * @param name the value for t_role.name
     *
     * @mbggenerated Thu Apr 23 15:14:51 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.roleKey
     *
     * @return the value of t_role.roleKey
     *
     * @mbggenerated Thu Apr 23 15:14:51 CST 2015
     */
    public String getRolekey() {
        return rolekey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.roleKey
     *
     * @param rolekey the value for t_role.roleKey
     *
     * @mbggenerated Thu Apr 23 15:14:51 CST 2015
     */
    public void setRolekey(String rolekey) {
        this.rolekey = rolekey == null ? null : rolekey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.description
     *
     * @return the value of t_role.description
     *
     * @mbggenerated Thu Apr 23 15:14:51 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.description
     *
     * @param description the value for t_role.description
     *
     * @mbggenerated Thu Apr 23 15:14:51 CST 2015
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.enable
     *
     * @return the value of t_role.enable
     *
     * @mbggenerated Thu Apr 23 15:14:51 CST 2015
     */
    public Integer getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.enable
     *
     * @param enable the value for t_role.enable
     *
     * @mbggenerated Thu Apr 23 15:14:51 CST 2015
     */
    public void setEnable(Integer enable) {
        this.enable = enable;
    }
}