package com.crab.entity;

import java.util.Date;

public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.userId
	 * @mbggenerated  Thu Apr 23 15:14:51 CST 2015
	 */
	private Integer userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.userName
	 * @mbggenerated  Thu Apr 23 15:14:51 CST 2015
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.userPassword
	 * @mbggenerated  Thu Apr 23 15:14:51 CST 2015
	 */
	private String userpassword;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.userNickname
	 * @mbggenerated  Thu Apr 23 15:14:51 CST 2015
	 */
	private String usernickname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.userRealname
	 * @mbggenerated  Thu Apr 23 15:14:51 CST 2015
	 */
	private String userrealname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.userAge
	 * @mbggenerated  Thu Apr 23 15:14:51 CST 2015
	 */
	private Integer userage;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.userSex
	 * @mbggenerated  Thu Apr 23 15:14:51 CST 2015
	 */
	private String usersex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.userAddress
	 * @mbggenerated  Thu Apr 23 15:14:51 CST 2015
	 */
	private String useraddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.userPhone
	 * @mbggenerated  Thu Apr 23 15:14:51 CST 2015
	 */
	private String userphone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.userMail
	 * @mbggenerated  Thu Apr 23 15:14:51 CST 2015
	 */
	private String usermail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.userQQ
	 * @mbggenerated  Thu Apr 23 15:14:51 CST 2015
	 */
	private String userqq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.regTime
	 * @mbggenerated  Thu Apr 23 15:14:51 CST 2015
	 */
	private Date regtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.lastLogintime
	 * @mbggenerated  Thu Apr 23 15:14:51 CST 2015
	 */
	private Date lastlogintime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.level
	 * @mbggenerated  Thu Apr 23 15:14:51 CST 2015
	 */
	private Integer level;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.userId
	 * @return  the value of t_user.userId
	 * @mbggenerated  Thu Apr 23 15:14:51 CST 2015
	 */
	public Integer getUserid()
	{
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.userId
	 * @param userid  the value for t_user.userId
	 * @mbggenerated  Thu Apr 23 15:14:51 CST 2015
	 */
	public void setUserid(Integer userid)
	{
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.userName
	 * @return  the value of t_user.userName
	 * @mbggenerated  Thu Apr 23 15:14:51 CST 2015
	 */
	public String getUsername()
	{
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.userName
	 * @param username  the value for t_user.userName
	 * @mbggenerated  Thu Apr 23 15:14:51 CST 2015
	 */
	public void setUsername(String username)
	{
		this.username = username == null ? null : username.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.userPassword
	 * @return  the value of t_user.userPassword
	 * @mbggenerated  Thu Apr 23 15:14:51 CST 2015
	 */
	public String getUserpassword()
	{
		return userpassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.userPassword
	 * @param userpassword  the value for t_user.userPassword
	 * @mbggenerated  Thu Apr 23 15:14:51 CST 2015
	 */
	public void setUserpassword(String userpassword)
	{
		this.userpassword = userpassword == null ? null : userpassword.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.userNickname
	 * @return  the value of t_user.userNickname
	 * @mbggenerated  Thu Apr 23 15:14:51 CST 2015
	 */
	public String getUsernickname()
	{
		return usernickname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.userNickname
	 * @param usernickname  the value for t_user.userNickname
	 * @mbggenerated  Thu Apr 23 15:14:51 CST 2015
	 */
	public void setUsernickname(String usernickname)
	{
		this.usernickname = usernickname == null ? null : usernickname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.userRealname
	 * @return  the value of t_user.userRealname
	 * @mbggenerated  Thu Apr 23 15:14:51 CST 2015
	 */
	public String getUserrealname()
	{
		return userrealname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.userRealname
	 * @param userrealname  the value for t_user.userRealname
	 * @mbggenerated  Thu Apr 23 15:14:51 CST 2015
	 */
	public void setUserrealname(String userrealname)
	{
		this.userrealname = userrealname == null ? null : userrealname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.userAge
	 * @return  the value of t_user.userAge
	 * @mbggenerated  Thu Apr 23 15:14:51 CST 2015
	 */
	public Integer getUserage()
	{
		return userage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.userAge
	 * @param userage  the value for t_user.userAge
	 * @mbggenerated  Thu Apr 23 15:14:51 CST 2015
	 */
	public void setUserage(Integer userage)
	{
		this.userage = userage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.userSex
	 * @return  the value of t_user.userSex
	 * @mbggenerated  Thu Apr 23 15:14:51 CST 2015
	 */
	public String getUsersex()
	{
		return usersex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.userSex
	 * @param usersex  the value for t_user.userSex
	 * @mbggenerated  Thu Apr 23 15:14:51 CST 2015
	 */
	public void setUsersex(String usersex)
	{
		this.usersex = usersex == null ? null : usersex.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.userAddress
	 * @return  the value of t_user.userAddress
	 * @mbggenerated  Thu Apr 23 15:14:51 CST 2015
	 */
	public String getUseraddress()
	{
		return useraddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.userAddress
	 * @param useraddress  the value for t_user.userAddress
	 * @mbggenerated  Thu Apr 23 15:14:51 CST 2015
	 */
	public void setUseraddress(String useraddress)
	{
		this.useraddress = useraddress == null ? null : useraddress.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.userPhone
	 * @return  the value of t_user.userPhone
	 * @mbggenerated  Thu Apr 23 15:14:51 CST 2015
	 */
	public String getUserphone()
	{
		return userphone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.userPhone
	 * @param userphone  the value for t_user.userPhone
	 * @mbggenerated  Thu Apr 23 15:14:51 CST 2015
	 */
	public void setUserphone(String userphone)
	{
		this.userphone = userphone == null ? null : userphone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.userMail
	 * @return  the value of t_user.userMail
	 * @mbggenerated  Thu Apr 23 15:14:51 CST 2015
	 */
	public String getUsermail()
	{
		return usermail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.userMail
	 * @param usermail  the value for t_user.userMail
	 * @mbggenerated  Thu Apr 23 15:14:51 CST 2015
	 */
	public void setUsermail(String usermail)
	{
		this.usermail = usermail == null ? null : usermail.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.userQQ
	 * @return  the value of t_user.userQQ
	 * @mbggenerated  Thu Apr 23 15:14:51 CST 2015
	 */
	public String getUserqq()
	{
		return userqq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.userQQ
	 * @param userqq  the value for t_user.userQQ
	 * @mbggenerated  Thu Apr 23 15:14:51 CST 2015
	 */
	public void setUserqq(String userqq)
	{
		this.userqq = userqq == null ? null : userqq.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.regTime
	 * @return  the value of t_user.regTime
	 * @mbggenerated  Thu Apr 23 15:14:51 CST 2015
	 */
	public Date getRegtime()
	{
		return regtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.regTime
	 * @param regtime  the value for t_user.regTime
	 * @mbggenerated  Thu Apr 23 15:14:51 CST 2015
	 */
	public void setRegtime(Date regtime)
	{
		this.regtime = regtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.lastLogintime
	 * @return  the value of t_user.lastLogintime
	 * @mbggenerated  Thu Apr 23 15:14:51 CST 2015
	 */
	public Date getLastlogintime()
	{
		return lastlogintime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.lastLogintime
	 * @param lastlogintime  the value for t_user.lastLogintime
	 * @mbggenerated  Thu Apr 23 15:14:51 CST 2015
	 */
	public void setLastlogintime(Date lastlogintime)
	{
		this.lastlogintime = lastlogintime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.level
	 * @return  the value of t_user.level
	 * @mbggenerated  Thu Apr 23 15:14:51 CST 2015
	 */
	public Integer getLevel()
	{
		return level;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.level
	 * @param level  the value for t_user.level
	 * @mbggenerated  Thu Apr 23 15:14:51 CST 2015
	 */
	public void setLevel(Integer level)
	{
		this.level = level;
	}
}