package com.crab.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_user
	 * @mbggenerated  Thu Apr 23 15:14:51 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_user
	 * @mbggenerated  Thu Apr 23 15:14:51 CST 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_user
	 * @mbggenerated  Thu Apr 23 15:14:51 CST 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbggenerated  Thu Apr 23 15:14:51 CST 2015
	 */
	public UserExample()
	{
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbggenerated  Thu Apr 23 15:14:51 CST 2015
	 */
	public void setOrderByClause(String orderByClause)
	{
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbggenerated  Thu Apr 23 15:14:51 CST 2015
	 */
	public String getOrderByClause()
	{
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbggenerated  Thu Apr 23 15:14:51 CST 2015
	 */
	public void setDistinct(boolean distinct)
	{
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbggenerated  Thu Apr 23 15:14:51 CST 2015
	 */
	public boolean isDistinct()
	{
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbggenerated  Thu Apr 23 15:14:51 CST 2015
	 */
	public List<Criteria> getOredCriteria()
	{
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbggenerated  Thu Apr 23 15:14:51 CST 2015
	 */
	public void or(Criteria criteria)
	{
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbggenerated  Thu Apr 23 15:14:51 CST 2015
	 */
	public Criteria or()
	{
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbggenerated  Thu Apr 23 15:14:51 CST 2015
	 */
	public Criteria createCriteria()
	{
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0)
		{
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbggenerated  Thu Apr 23 15:14:51 CST 2015
	 */
	protected Criteria createCriteriaInternal()
	{
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbggenerated  Thu Apr 23 15:14:51 CST 2015
	 */
	public void clear()
	{
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_user
	 * @mbggenerated  Thu Apr 23 15:14:51 CST 2015
	 */
	protected abstract static class GeneratedCriteria
	{
		protected List<Criterion> criteria;

		protected GeneratedCriteria()
		{
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid()
		{
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria()
		{
			return criteria;
		}

		public List<Criterion> getCriteria()
		{
			return criteria;
		}

		protected void addCriterion(String condition)
		{
			if (condition == null)
			{
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property)
		{
			if (value == null)
			{
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property)
		{
			if (value1 == null || value2 == null)
			{
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andUseridIsNull()
		{
			addCriterion("userId is null");
			return (Criteria) this;
		}

		public Criteria andUseridIsNotNull()
		{
			addCriterion("userId is not null");
			return (Criteria) this;
		}

		public Criteria andUseridEqualTo(Integer value)
		{
			addCriterion("userId =", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotEqualTo(Integer value)
		{
			addCriterion("userId <>", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridGreaterThan(Integer value)
		{
			addCriterion("userId >", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridGreaterThanOrEqualTo(Integer value)
		{
			addCriterion("userId >=", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridLessThan(Integer value)
		{
			addCriterion("userId <", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridLessThanOrEqualTo(Integer value)
		{
			addCriterion("userId <=", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridIn(List<Integer> values)
		{
			addCriterion("userId in", values, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotIn(List<Integer> values)
		{
			addCriterion("userId not in", values, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridBetween(Integer value1, Integer value2)
		{
			addCriterion("userId between", value1, value2, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotBetween(Integer value1, Integer value2)
		{
			addCriterion("userId not between", value1, value2, "userid");
			return (Criteria) this;
		}

		public Criteria andUsernameIsNull()
		{
			addCriterion("userName is null");
			return (Criteria) this;
		}

		public Criteria andUsernameIsNotNull()
		{
			addCriterion("userName is not null");
			return (Criteria) this;
		}

		public Criteria andUsernameEqualTo(String value)
		{
			addCriterion("userName =", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotEqualTo(String value)
		{
			addCriterion("userName <>", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameGreaterThan(String value)
		{
			addCriterion("userName >", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameGreaterThanOrEqualTo(String value)
		{
			addCriterion("userName >=", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameLessThan(String value)
		{
			addCriterion("userName <", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameLessThanOrEqualTo(String value)
		{
			addCriterion("userName <=", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameLike(String value)
		{
			addCriterion("userName like", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotLike(String value)
		{
			addCriterion("userName not like", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameIn(List<String> values)
		{
			addCriterion("userName in", values, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotIn(List<String> values)
		{
			addCriterion("userName not in", values, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameBetween(String value1, String value2)
		{
			addCriterion("userName between", value1, value2, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotBetween(String value1, String value2)
		{
			addCriterion("userName not between", value1, value2, "username");
			return (Criteria) this;
		}

		public Criteria andUserpasswordIsNull()
		{
			addCriterion("userPassword is null");
			return (Criteria) this;
		}

		public Criteria andUserpasswordIsNotNull()
		{
			addCriterion("userPassword is not null");
			return (Criteria) this;
		}

		public Criteria andUserpasswordEqualTo(String value)
		{
			addCriterion("userPassword =", value, "userpassword");
			return (Criteria) this;
		}

		public Criteria andUserpasswordNotEqualTo(String value)
		{
			addCriterion("userPassword <>", value, "userpassword");
			return (Criteria) this;
		}

		public Criteria andUserpasswordGreaterThan(String value)
		{
			addCriterion("userPassword >", value, "userpassword");
			return (Criteria) this;
		}

		public Criteria andUserpasswordGreaterThanOrEqualTo(String value)
		{
			addCriterion("userPassword >=", value, "userpassword");
			return (Criteria) this;
		}

		public Criteria andUserpasswordLessThan(String value)
		{
			addCriterion("userPassword <", value, "userpassword");
			return (Criteria) this;
		}

		public Criteria andUserpasswordLessThanOrEqualTo(String value)
		{
			addCriterion("userPassword <=", value, "userpassword");
			return (Criteria) this;
		}

		public Criteria andUserpasswordLike(String value)
		{
			addCriterion("userPassword like", value, "userpassword");
			return (Criteria) this;
		}

		public Criteria andUserpasswordNotLike(String value)
		{
			addCriterion("userPassword not like", value, "userpassword");
			return (Criteria) this;
		}

		public Criteria andUserpasswordIn(List<String> values)
		{
			addCriterion("userPassword in", values, "userpassword");
			return (Criteria) this;
		}

		public Criteria andUserpasswordNotIn(List<String> values)
		{
			addCriterion("userPassword not in", values, "userpassword");
			return (Criteria) this;
		}

		public Criteria andUserpasswordBetween(String value1, String value2)
		{
			addCriterion("userPassword between", value1, value2, "userpassword");
			return (Criteria) this;
		}

		public Criteria andUserpasswordNotBetween(String value1, String value2)
		{
			addCriterion("userPassword not between", value1, value2, "userpassword");
			return (Criteria) this;
		}

		public Criteria andUsernicknameIsNull()
		{
			addCriterion("userNickname is null");
			return (Criteria) this;
		}

		public Criteria andUsernicknameIsNotNull()
		{
			addCriterion("userNickname is not null");
			return (Criteria) this;
		}

		public Criteria andUsernicknameEqualTo(String value)
		{
			addCriterion("userNickname =", value, "usernickname");
			return (Criteria) this;
		}

		public Criteria andUsernicknameNotEqualTo(String value)
		{
			addCriterion("userNickname <>", value, "usernickname");
			return (Criteria) this;
		}

		public Criteria andUsernicknameGreaterThan(String value)
		{
			addCriterion("userNickname >", value, "usernickname");
			return (Criteria) this;
		}

		public Criteria andUsernicknameGreaterThanOrEqualTo(String value)
		{
			addCriterion("userNickname >=", value, "usernickname");
			return (Criteria) this;
		}

		public Criteria andUsernicknameLessThan(String value)
		{
			addCriterion("userNickname <", value, "usernickname");
			return (Criteria) this;
		}

		public Criteria andUsernicknameLessThanOrEqualTo(String value)
		{
			addCriterion("userNickname <=", value, "usernickname");
			return (Criteria) this;
		}

		public Criteria andUsernicknameLike(String value)
		{
			addCriterion("userNickname like", value, "usernickname");
			return (Criteria) this;
		}

		public Criteria andUsernicknameNotLike(String value)
		{
			addCriterion("userNickname not like", value, "usernickname");
			return (Criteria) this;
		}

		public Criteria andUsernicknameIn(List<String> values)
		{
			addCriterion("userNickname in", values, "usernickname");
			return (Criteria) this;
		}

		public Criteria andUsernicknameNotIn(List<String> values)
		{
			addCriterion("userNickname not in", values, "usernickname");
			return (Criteria) this;
		}

		public Criteria andUsernicknameBetween(String value1, String value2)
		{
			addCriterion("userNickname between", value1, value2, "usernickname");
			return (Criteria) this;
		}

		public Criteria andUsernicknameNotBetween(String value1, String value2)
		{
			addCriterion("userNickname not between", value1, value2, "usernickname");
			return (Criteria) this;
		}

		public Criteria andUserrealnameIsNull()
		{
			addCriterion("userRealname is null");
			return (Criteria) this;
		}

		public Criteria andUserrealnameIsNotNull()
		{
			addCriterion("userRealname is not null");
			return (Criteria) this;
		}

		public Criteria andUserrealnameEqualTo(String value)
		{
			addCriterion("userRealname =", value, "userrealname");
			return (Criteria) this;
		}

		public Criteria andUserrealnameNotEqualTo(String value)
		{
			addCriterion("userRealname <>", value, "userrealname");
			return (Criteria) this;
		}

		public Criteria andUserrealnameGreaterThan(String value)
		{
			addCriterion("userRealname >", value, "userrealname");
			return (Criteria) this;
		}

		public Criteria andUserrealnameGreaterThanOrEqualTo(String value)
		{
			addCriterion("userRealname >=", value, "userrealname");
			return (Criteria) this;
		}

		public Criteria andUserrealnameLessThan(String value)
		{
			addCriterion("userRealname <", value, "userrealname");
			return (Criteria) this;
		}

		public Criteria andUserrealnameLessThanOrEqualTo(String value)
		{
			addCriterion("userRealname <=", value, "userrealname");
			return (Criteria) this;
		}

		public Criteria andUserrealnameLike(String value)
		{
			addCriterion("userRealname like", value, "userrealname");
			return (Criteria) this;
		}

		public Criteria andUserrealnameNotLike(String value)
		{
			addCriterion("userRealname not like", value, "userrealname");
			return (Criteria) this;
		}

		public Criteria andUserrealnameIn(List<String> values)
		{
			addCriterion("userRealname in", values, "userrealname");
			return (Criteria) this;
		}

		public Criteria andUserrealnameNotIn(List<String> values)
		{
			addCriterion("userRealname not in", values, "userrealname");
			return (Criteria) this;
		}

		public Criteria andUserrealnameBetween(String value1, String value2)
		{
			addCriterion("userRealname between", value1, value2, "userrealname");
			return (Criteria) this;
		}

		public Criteria andUserrealnameNotBetween(String value1, String value2)
		{
			addCriterion("userRealname not between", value1, value2, "userrealname");
			return (Criteria) this;
		}

		public Criteria andUserageIsNull()
		{
			addCriterion("userAge is null");
			return (Criteria) this;
		}

		public Criteria andUserageIsNotNull()
		{
			addCriterion("userAge is not null");
			return (Criteria) this;
		}

		public Criteria andUserageEqualTo(Integer value)
		{
			addCriterion("userAge =", value, "userage");
			return (Criteria) this;
		}

		public Criteria andUserageNotEqualTo(Integer value)
		{
			addCriterion("userAge <>", value, "userage");
			return (Criteria) this;
		}

		public Criteria andUserageGreaterThan(Integer value)
		{
			addCriterion("userAge >", value, "userage");
			return (Criteria) this;
		}

		public Criteria andUserageGreaterThanOrEqualTo(Integer value)
		{
			addCriterion("userAge >=", value, "userage");
			return (Criteria) this;
		}

		public Criteria andUserageLessThan(Integer value)
		{
			addCriterion("userAge <", value, "userage");
			return (Criteria) this;
		}

		public Criteria andUserageLessThanOrEqualTo(Integer value)
		{
			addCriterion("userAge <=", value, "userage");
			return (Criteria) this;
		}

		public Criteria andUserageIn(List<Integer> values)
		{
			addCriterion("userAge in", values, "userage");
			return (Criteria) this;
		}

		public Criteria andUserageNotIn(List<Integer> values)
		{
			addCriterion("userAge not in", values, "userage");
			return (Criteria) this;
		}

		public Criteria andUserageBetween(Integer value1, Integer value2)
		{
			addCriterion("userAge between", value1, value2, "userage");
			return (Criteria) this;
		}

		public Criteria andUserageNotBetween(Integer value1, Integer value2)
		{
			addCriterion("userAge not between", value1, value2, "userage");
			return (Criteria) this;
		}

		public Criteria andUsersexIsNull()
		{
			addCriterion("userSex is null");
			return (Criteria) this;
		}

		public Criteria andUsersexIsNotNull()
		{
			addCriterion("userSex is not null");
			return (Criteria) this;
		}

		public Criteria andUsersexEqualTo(String value)
		{
			addCriterion("userSex =", value, "usersex");
			return (Criteria) this;
		}

		public Criteria andUsersexNotEqualTo(String value)
		{
			addCriterion("userSex <>", value, "usersex");
			return (Criteria) this;
		}

		public Criteria andUsersexGreaterThan(String value)
		{
			addCriterion("userSex >", value, "usersex");
			return (Criteria) this;
		}

		public Criteria andUsersexGreaterThanOrEqualTo(String value)
		{
			addCriterion("userSex >=", value, "usersex");
			return (Criteria) this;
		}

		public Criteria andUsersexLessThan(String value)
		{
			addCriterion("userSex <", value, "usersex");
			return (Criteria) this;
		}

		public Criteria andUsersexLessThanOrEqualTo(String value)
		{
			addCriterion("userSex <=", value, "usersex");
			return (Criteria) this;
		}

		public Criteria andUsersexLike(String value)
		{
			addCriterion("userSex like", value, "usersex");
			return (Criteria) this;
		}

		public Criteria andUsersexNotLike(String value)
		{
			addCriterion("userSex not like", value, "usersex");
			return (Criteria) this;
		}

		public Criteria andUsersexIn(List<String> values)
		{
			addCriterion("userSex in", values, "usersex");
			return (Criteria) this;
		}

		public Criteria andUsersexNotIn(List<String> values)
		{
			addCriterion("userSex not in", values, "usersex");
			return (Criteria) this;
		}

		public Criteria andUsersexBetween(String value1, String value2)
		{
			addCriterion("userSex between", value1, value2, "usersex");
			return (Criteria) this;
		}

		public Criteria andUsersexNotBetween(String value1, String value2)
		{
			addCriterion("userSex not between", value1, value2, "usersex");
			return (Criteria) this;
		}

		public Criteria andUseraddressIsNull()
		{
			addCriterion("userAddress is null");
			return (Criteria) this;
		}

		public Criteria andUseraddressIsNotNull()
		{
			addCriterion("userAddress is not null");
			return (Criteria) this;
		}

		public Criteria andUseraddressEqualTo(String value)
		{
			addCriterion("userAddress =", value, "useraddress");
			return (Criteria) this;
		}

		public Criteria andUseraddressNotEqualTo(String value)
		{
			addCriterion("userAddress <>", value, "useraddress");
			return (Criteria) this;
		}

		public Criteria andUseraddressGreaterThan(String value)
		{
			addCriterion("userAddress >", value, "useraddress");
			return (Criteria) this;
		}

		public Criteria andUseraddressGreaterThanOrEqualTo(String value)
		{
			addCriterion("userAddress >=", value, "useraddress");
			return (Criteria) this;
		}

		public Criteria andUseraddressLessThan(String value)
		{
			addCriterion("userAddress <", value, "useraddress");
			return (Criteria) this;
		}

		public Criteria andUseraddressLessThanOrEqualTo(String value)
		{
			addCriterion("userAddress <=", value, "useraddress");
			return (Criteria) this;
		}

		public Criteria andUseraddressLike(String value)
		{
			addCriterion("userAddress like", value, "useraddress");
			return (Criteria) this;
		}

		public Criteria andUseraddressNotLike(String value)
		{
			addCriterion("userAddress not like", value, "useraddress");
			return (Criteria) this;
		}

		public Criteria andUseraddressIn(List<String> values)
		{
			addCriterion("userAddress in", values, "useraddress");
			return (Criteria) this;
		}

		public Criteria andUseraddressNotIn(List<String> values)
		{
			addCriterion("userAddress not in", values, "useraddress");
			return (Criteria) this;
		}

		public Criteria andUseraddressBetween(String value1, String value2)
		{
			addCriterion("userAddress between", value1, value2, "useraddress");
			return (Criteria) this;
		}

		public Criteria andUseraddressNotBetween(String value1, String value2)
		{
			addCriterion("userAddress not between", value1, value2, "useraddress");
			return (Criteria) this;
		}

		public Criteria andUserphoneIsNull()
		{
			addCriterion("userPhone is null");
			return (Criteria) this;
		}

		public Criteria andUserphoneIsNotNull()
		{
			addCriterion("userPhone is not null");
			return (Criteria) this;
		}

		public Criteria andUserphoneEqualTo(String value)
		{
			addCriterion("userPhone =", value, "userphone");
			return (Criteria) this;
		}

		public Criteria andUserphoneNotEqualTo(String value)
		{
			addCriterion("userPhone <>", value, "userphone");
			return (Criteria) this;
		}

		public Criteria andUserphoneGreaterThan(String value)
		{
			addCriterion("userPhone >", value, "userphone");
			return (Criteria) this;
		}

		public Criteria andUserphoneGreaterThanOrEqualTo(String value)
		{
			addCriterion("userPhone >=", value, "userphone");
			return (Criteria) this;
		}

		public Criteria andUserphoneLessThan(String value)
		{
			addCriterion("userPhone <", value, "userphone");
			return (Criteria) this;
		}

		public Criteria andUserphoneLessThanOrEqualTo(String value)
		{
			addCriterion("userPhone <=", value, "userphone");
			return (Criteria) this;
		}

		public Criteria andUserphoneLike(String value)
		{
			addCriterion("userPhone like", value, "userphone");
			return (Criteria) this;
		}

		public Criteria andUserphoneNotLike(String value)
		{
			addCriterion("userPhone not like", value, "userphone");
			return (Criteria) this;
		}

		public Criteria andUserphoneIn(List<String> values)
		{
			addCriterion("userPhone in", values, "userphone");
			return (Criteria) this;
		}

		public Criteria andUserphoneNotIn(List<String> values)
		{
			addCriterion("userPhone not in", values, "userphone");
			return (Criteria) this;
		}

		public Criteria andUserphoneBetween(String value1, String value2)
		{
			addCriterion("userPhone between", value1, value2, "userphone");
			return (Criteria) this;
		}

		public Criteria andUserphoneNotBetween(String value1, String value2)
		{
			addCriterion("userPhone not between", value1, value2, "userphone");
			return (Criteria) this;
		}

		public Criteria andUsermailIsNull()
		{
			addCriterion("userMail is null");
			return (Criteria) this;
		}

		public Criteria andUsermailIsNotNull()
		{
			addCriterion("userMail is not null");
			return (Criteria) this;
		}

		public Criteria andUsermailEqualTo(String value)
		{
			addCriterion("userMail =", value, "usermail");
			return (Criteria) this;
		}

		public Criteria andUsermailNotEqualTo(String value)
		{
			addCriterion("userMail <>", value, "usermail");
			return (Criteria) this;
		}

		public Criteria andUsermailGreaterThan(String value)
		{
			addCriterion("userMail >", value, "usermail");
			return (Criteria) this;
		}

		public Criteria andUsermailGreaterThanOrEqualTo(String value)
		{
			addCriterion("userMail >=", value, "usermail");
			return (Criteria) this;
		}

		public Criteria andUsermailLessThan(String value)
		{
			addCriterion("userMail <", value, "usermail");
			return (Criteria) this;
		}

		public Criteria andUsermailLessThanOrEqualTo(String value)
		{
			addCriterion("userMail <=", value, "usermail");
			return (Criteria) this;
		}

		public Criteria andUsermailLike(String value)
		{
			addCriterion("userMail like", value, "usermail");
			return (Criteria) this;
		}

		public Criteria andUsermailNotLike(String value)
		{
			addCriterion("userMail not like", value, "usermail");
			return (Criteria) this;
		}

		public Criteria andUsermailIn(List<String> values)
		{
			addCriterion("userMail in", values, "usermail");
			return (Criteria) this;
		}

		public Criteria andUsermailNotIn(List<String> values)
		{
			addCriterion("userMail not in", values, "usermail");
			return (Criteria) this;
		}

		public Criteria andUsermailBetween(String value1, String value2)
		{
			addCriterion("userMail between", value1, value2, "usermail");
			return (Criteria) this;
		}

		public Criteria andUsermailNotBetween(String value1, String value2)
		{
			addCriterion("userMail not between", value1, value2, "usermail");
			return (Criteria) this;
		}

		public Criteria andUserqqIsNull()
		{
			addCriterion("userQQ is null");
			return (Criteria) this;
		}

		public Criteria andUserqqIsNotNull()
		{
			addCriterion("userQQ is not null");
			return (Criteria) this;
		}

		public Criteria andUserqqEqualTo(String value)
		{
			addCriterion("userQQ =", value, "userqq");
			return (Criteria) this;
		}

		public Criteria andUserqqNotEqualTo(String value)
		{
			addCriterion("userQQ <>", value, "userqq");
			return (Criteria) this;
		}

		public Criteria andUserqqGreaterThan(String value)
		{
			addCriterion("userQQ >", value, "userqq");
			return (Criteria) this;
		}

		public Criteria andUserqqGreaterThanOrEqualTo(String value)
		{
			addCriterion("userQQ >=", value, "userqq");
			return (Criteria) this;
		}

		public Criteria andUserqqLessThan(String value)
		{
			addCriterion("userQQ <", value, "userqq");
			return (Criteria) this;
		}

		public Criteria andUserqqLessThanOrEqualTo(String value)
		{
			addCriterion("userQQ <=", value, "userqq");
			return (Criteria) this;
		}

		public Criteria andUserqqLike(String value)
		{
			addCriterion("userQQ like", value, "userqq");
			return (Criteria) this;
		}

		public Criteria andUserqqNotLike(String value)
		{
			addCriterion("userQQ not like", value, "userqq");
			return (Criteria) this;
		}

		public Criteria andUserqqIn(List<String> values)
		{
			addCriterion("userQQ in", values, "userqq");
			return (Criteria) this;
		}

		public Criteria andUserqqNotIn(List<String> values)
		{
			addCriterion("userQQ not in", values, "userqq");
			return (Criteria) this;
		}

		public Criteria andUserqqBetween(String value1, String value2)
		{
			addCriterion("userQQ between", value1, value2, "userqq");
			return (Criteria) this;
		}

		public Criteria andUserqqNotBetween(String value1, String value2)
		{
			addCriterion("userQQ not between", value1, value2, "userqq");
			return (Criteria) this;
		}

		public Criteria andRegtimeIsNull()
		{
			addCriterion("regTime is null");
			return (Criteria) this;
		}

		public Criteria andRegtimeIsNotNull()
		{
			addCriterion("regTime is not null");
			return (Criteria) this;
		}

		public Criteria andRegtimeEqualTo(Date value)
		{
			addCriterion("regTime =", value, "regtime");
			return (Criteria) this;
		}

		public Criteria andRegtimeNotEqualTo(Date value)
		{
			addCriterion("regTime <>", value, "regtime");
			return (Criteria) this;
		}

		public Criteria andRegtimeGreaterThan(Date value)
		{
			addCriterion("regTime >", value, "regtime");
			return (Criteria) this;
		}

		public Criteria andRegtimeGreaterThanOrEqualTo(Date value)
		{
			addCriterion("regTime >=", value, "regtime");
			return (Criteria) this;
		}

		public Criteria andRegtimeLessThan(Date value)
		{
			addCriterion("regTime <", value, "regtime");
			return (Criteria) this;
		}

		public Criteria andRegtimeLessThanOrEqualTo(Date value)
		{
			addCriterion("regTime <=", value, "regtime");
			return (Criteria) this;
		}

		public Criteria andRegtimeIn(List<Date> values)
		{
			addCriterion("regTime in", values, "regtime");
			return (Criteria) this;
		}

		public Criteria andRegtimeNotIn(List<Date> values)
		{
			addCriterion("regTime not in", values, "regtime");
			return (Criteria) this;
		}

		public Criteria andRegtimeBetween(Date value1, Date value2)
		{
			addCriterion("regTime between", value1, value2, "regtime");
			return (Criteria) this;
		}

		public Criteria andRegtimeNotBetween(Date value1, Date value2)
		{
			addCriterion("regTime not between", value1, value2, "regtime");
			return (Criteria) this;
		}

		public Criteria andLastlogintimeIsNull()
		{
			addCriterion("lastLogintime is null");
			return (Criteria) this;
		}

		public Criteria andLastlogintimeIsNotNull()
		{
			addCriterion("lastLogintime is not null");
			return (Criteria) this;
		}

		public Criteria andLastlogintimeEqualTo(Date value)
		{
			addCriterion("lastLogintime =", value, "lastlogintime");
			return (Criteria) this;
		}

		public Criteria andLastlogintimeNotEqualTo(Date value)
		{
			addCriterion("lastLogintime <>", value, "lastlogintime");
			return (Criteria) this;
		}

		public Criteria andLastlogintimeGreaterThan(Date value)
		{
			addCriterion("lastLogintime >", value, "lastlogintime");
			return (Criteria) this;
		}

		public Criteria andLastlogintimeGreaterThanOrEqualTo(Date value)
		{
			addCriterion("lastLogintime >=", value, "lastlogintime");
			return (Criteria) this;
		}

		public Criteria andLastlogintimeLessThan(Date value)
		{
			addCriterion("lastLogintime <", value, "lastlogintime");
			return (Criteria) this;
		}

		public Criteria andLastlogintimeLessThanOrEqualTo(Date value)
		{
			addCriterion("lastLogintime <=", value, "lastlogintime");
			return (Criteria) this;
		}

		public Criteria andLastlogintimeIn(List<Date> values)
		{
			addCriterion("lastLogintime in", values, "lastlogintime");
			return (Criteria) this;
		}

		public Criteria andLastlogintimeNotIn(List<Date> values)
		{
			addCriterion("lastLogintime not in", values, "lastlogintime");
			return (Criteria) this;
		}

		public Criteria andLastlogintimeBetween(Date value1, Date value2)
		{
			addCriterion("lastLogintime between", value1, value2, "lastlogintime");
			return (Criteria) this;
		}

		public Criteria andLastlogintimeNotBetween(Date value1, Date value2)
		{
			addCriterion("lastLogintime not between", value1, value2, "lastlogintime");
			return (Criteria) this;
		}

		public Criteria andLevelIsNull()
		{
			addCriterion("level is null");
			return (Criteria) this;
		}

		public Criteria andLevelIsNotNull()
		{
			addCriterion("level is not null");
			return (Criteria) this;
		}

		public Criteria andLevelEqualTo(Integer value)
		{
			addCriterion("level =", value, "level");
			return (Criteria) this;
		}

		public Criteria andLevelNotEqualTo(Integer value)
		{
			addCriterion("level <>", value, "level");
			return (Criteria) this;
		}

		public Criteria andLevelGreaterThan(Integer value)
		{
			addCriterion("level >", value, "level");
			return (Criteria) this;
		}

		public Criteria andLevelGreaterThanOrEqualTo(Integer value)
		{
			addCriterion("level >=", value, "level");
			return (Criteria) this;
		}

		public Criteria andLevelLessThan(Integer value)
		{
			addCriterion("level <", value, "level");
			return (Criteria) this;
		}

		public Criteria andLevelLessThanOrEqualTo(Integer value)
		{
			addCriterion("level <=", value, "level");
			return (Criteria) this;
		}

		public Criteria andLevelIn(List<Integer> values)
		{
			addCriterion("level in", values, "level");
			return (Criteria) this;
		}

		public Criteria andLevelNotIn(List<Integer> values)
		{
			addCriterion("level not in", values, "level");
			return (Criteria) this;
		}

		public Criteria andLevelBetween(Integer value1, Integer value2)
		{
			addCriterion("level between", value1, value2, "level");
			return (Criteria) this;
		}

		public Criteria andLevelNotBetween(Integer value1, Integer value2)
		{
			addCriterion("level not between", value1, value2, "level");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_user
	 * @mbggenerated  Thu Apr 23 15:14:51 CST 2015
	 */
	public static class Criterion
	{
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition()
		{
			return condition;
		}

		public Object getValue()
		{
			return value;
		}

		public Object getSecondValue()
		{
			return secondValue;
		}

		public boolean isNoValue()
		{
			return noValue;
		}

		public boolean isSingleValue()
		{
			return singleValue;
		}

		public boolean isBetweenValue()
		{
			return betweenValue;
		}

		public boolean isListValue()
		{
			return listValue;
		}

		public String getTypeHandler()
		{
			return typeHandler;
		}

		protected Criterion(String condition)
		{
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler)
		{
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>)
			{
				this.listValue = true;
			}
			else
			{
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value)
		{
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler)
		{
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue)
		{
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_user
     *
     * @mbggenerated do_not_delete_during_merge Thu Apr 23 15:12:27 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}