package com.crab.dao;

import com.crab.entity.ResourceRoleLinkExample;
import com.crab.entity.ResourceRoleLinkKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ResourceRoleLinkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource_role
     *
     * @mbggenerated Fri Apr 24 13:16:32 CST 2015
     */
    int countByExample(ResourceRoleLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource_role
     *
     * @mbggenerated Fri Apr 24 13:16:32 CST 2015
     */
    int deleteByExample(ResourceRoleLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource_role
     *
     * @mbggenerated Fri Apr 24 13:16:32 CST 2015
     */
    int deleteByPrimaryKey(ResourceRoleLinkKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource_role
     *
     * @mbggenerated Fri Apr 24 13:16:32 CST 2015
     */
    int insert(ResourceRoleLinkKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource_role
     *
     * @mbggenerated Fri Apr 24 13:16:32 CST 2015
     */
    int insertSelective(ResourceRoleLinkKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource_role
     *
     * @mbggenerated Fri Apr 24 13:16:32 CST 2015
     */
    List<ResourceRoleLinkKey> selectByExample(ResourceRoleLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource_role
     *
     * @mbggenerated Fri Apr 24 13:16:32 CST 2015
     */
    int updateByExampleSelective(@Param("record") ResourceRoleLinkKey record, @Param("example") ResourceRoleLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource_role
     *
     * @mbggenerated Fri Apr 24 13:16:32 CST 2015
     */
    int updateByExample(@Param("record") ResourceRoleLinkKey record, @Param("example") ResourceRoleLinkExample example);
}