package com.crab.dao;

import com.crab.entity.UserRoleLinkExample;
import com.crab.entity.UserRoleLinkKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserRoleLinkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_role
     *
     * @mbggenerated Fri Apr 24 13:16:32 CST 2015
     */
    int countByExample(UserRoleLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_role
     *
     * @mbggenerated Fri Apr 24 13:16:32 CST 2015
     */
    int deleteByExample(UserRoleLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_role
     *
     * @mbggenerated Fri Apr 24 13:16:32 CST 2015
     */
    int deleteByPrimaryKey(UserRoleLinkKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_role
     *
     * @mbggenerated Fri Apr 24 13:16:32 CST 2015
     */
    int insert(UserRoleLinkKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_role
     *
     * @mbggenerated Fri Apr 24 13:16:32 CST 2015
     */
    int insertSelective(UserRoleLinkKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_role
     *
     * @mbggenerated Fri Apr 24 13:16:32 CST 2015
     */
    List<UserRoleLinkKey> selectByExample(UserRoleLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_role
     *
     * @mbggenerated Fri Apr 24 13:16:32 CST 2015
     */
    int updateByExampleSelective(@Param("record") UserRoleLinkKey record, @Param("example") UserRoleLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_role
     *
     * @mbggenerated Fri Apr 24 13:16:32 CST 2015
     */
    int updateByExample(@Param("record") UserRoleLinkKey record, @Param("example") UserRoleLinkExample example);
}